services:
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: rianmostert
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/app/db:/docker-entrypoint-initdb.d:ro

  backend:
    build: ./backend
    container_name: fastapi-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://rianmostert:password@postgres:5432/mydb
      - FRONTEND_URL=*
      - ENV=dev
      - JSON_STORAGE_PATH=storage/json/
      - QUESTION_PAPER_STORAGE_FOLDER=storage/pdfs/question_papers/
      - ANSWER_SHEET_STORAGE_FOLDER=storage/pdfs/answer_sheets/
      - ANNOTATION_STORAGE_FOLDER=storage/jsons/annotations/
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: nextjs-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
      - CI=true
    depends_on:
      - backend
    command: >
      sh -lc "
        rm -rf /app/node_modules/* &&
        pnpm install --frozen-lockfile --force &&
        pnpm dev
      "

volumes:
  postgres_data:
